### ISSUE TITLE
QA | HTML checklist

### ISSUE THREAD

**Issue by phungrk** [x-riv/repo25.ryukyu-i-dev.com#1]
**Checklist:**

- [ ] HTML5 Semantic Elements are used appropriately (header, section, footer, main...)
- [ ] Error pages: Error 404 page and 5xx exist
- [ ] W3C compliant: All pages need to be tested with the W3C validator to identify possible issues in the HTML code.
- [ ] Link checker: There are no broken links in my page, verify that you don't have any 404 error.

**Tools:**

- HTML5 Semantic Elements: https://www.w3schools.com/html/html5_semantic_elements.asp
- HTML5 Outliner: https://chrome.google.com/webstore/detail/html5-outliner/afoibpobokebhgfnknfndkgemglggomo?hl=ja
- W3C validator: https://validator.w3.org/
- W3C chrome extension: https://chrome.google.com/webstore/detail/w3c-validator/pbaecdpmkegnbfaholbenimmfikckdlk
- Link checker chrome extension: https://chrome.google.com/webstore/detail/check-my-links/ojkcdipcgfaekbeaelaapakgnjflfglf
